import NivatTrial.OneSided
import NivatTrial.Geometry
import Mathlib.Algebra.MonoidAlgebra.MapDomain
import Mathlib.Algebra.MonoidAlgebra.Basic
import Mathlib.Algebra.Ring.GeomSum
import Mathlib.RingTheory.PowerBasis
import Mathlib.Algebra.Algebra.Operations
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.LinearAlgebra.Dimension.Constructions

/-!
# Evaluation and prime binomial factors in the Laurent ring

Evaluation at a nonzero value of the first coordinate is a ring homomorphism
to the Laurent ring in the second coordinate. Its kernel is generated by the
corresponding linear binomial. Coordinate changes transport this statement to
every primitive lattice direction.
-/

namespace NivatTrial.Divisibility

open NivatTrial.Algebra

abbrev Laurent1 := OneSided.Laurent1

noncomputable section

def monomial (v : G) : Laurent := AddMonoidAlgebra.single v 1

def scalar : ℂ →+* Laurent := AddMonoidAlgebra.singleZeroRingHom

def binomial (v : G) (lam : ℂ) : Laurent := monomial v - scalar lam

@[simp] theorem monomial_zero : monomial 0 = 1 := rfl

@[simp] theorem monomial_add (u v : G) :
    monomial (u + v) = monomial u * monomial v := by
  simp [monomial]

@[simp] theorem scalar_apply (c : ℂ) : scalar c = AddMonoidAlgebra.single 0 c := rfl

theorem scalar_mul_monomial (v : G) (c : ℂ) :
    scalar c * monomial v = AddMonoidAlgebra.single v c := by
  simp [monomial]

def monomialUnit (v : G) : Laurentˣ where
  val := monomial v
  inv := monomial (-v)
  val_inv := by rw [← monomial_add, add_neg_cancel, monomial_zero]
  inv_val := by rw [← monomial_add, neg_add_cancel, monomial_zero]

@[simp] theorem monomialUnit_val (v : G) : (monomialUnit v : Laurent) = monomial v := rfl

theorem monomialUnit_zpow (v : G) (n : ℤ) :
    ((monomialUnit v ^ n : Laurentˣ) : Laurent) = monomial (n • v) := by
  cases n with
  | ofNat n => simp [monomial, AddMonoidAlgebra.single_pow]
  | negSucc n =>
    rw [show Int.negSucc n = -((n + 1 : ℕ) : ℤ) by omega, zpow_neg, zpow_natCast,
      ← inv_pow]
    simp [monomialUnit, monomial, AddMonoidAlgebra.single_pow]
    congr 1
    ext <;> simp <;> ring

def scalarUnit (lam : ℂˣ) : Laurentˣ := Units.map scalar.toMonoidHom lam

@[simp] theorem scalarUnit_val (lam : ℂˣ) :
    (scalarUnit lam : Laurent) = scalar (lam : ℂ) := rfl

theorem scalarUnit_zpow (lam : ℂˣ) (n : ℤ) :
    ((scalarUnit lam ^ n : Laurentˣ) : Laurent) = scalar ((lam ^ n : ℂˣ) : ℂ) := by
  exact congrArg (fun a : Laurentˣ => (a : Laurent)) (map_zpow (Units.map scalar.toMonoidHom) lam n).symm

/-- The factor theorem also holds for negative powers of units. -/
theorem unit_sub_dvd_zpow_sub_zpow {R : Type*} [CommRing R] (a b : Rˣ) (n : ℤ) :
    (a : R) - (b : R) ∣ ((a ^ n : Rˣ) : R) - ((b ^ n : Rˣ) : R) := by
  have hinv : (a : R) - (b : R) ∣ (a⁻¹ : Rˣ) - (b⁻¹ : Rˣ) := by
    refine ⟨-((a⁻¹ : Rˣ) : R) * ((b⁻¹ : Rˣ) : R), ?_⟩
    calc
      ((a⁻¹ : Rˣ) : R) - ((b⁻¹ : Rˣ) : R) =
          ((a⁻¹ : Rˣ) : R) * ((b : R) * ((b⁻¹ : Rˣ) : R)) -
            ((b⁻¹ : Rˣ) : R) * ((a : R) * ((a⁻¹ : Rˣ) : R)) := by simp
      _ = ((a : R) - (b : R)) * (-((a⁻¹ : Rˣ) : R) * ((b⁻¹ : Rˣ) : R)) := by ring
  cases n with
  | ofNat n => simpa using sub_dvd_pow_sub_pow (a : R) (b : R) n
  | negSucc n =>
    have hpow := sub_dvd_pow_sub_pow (((a⁻¹ : Rˣ) : R)) (((b⁻¹ : Rˣ) : R)) (n + 1)
    rw [show Int.negSucc n = -((n + 1 : ℕ) : ℤ) by omega]
    simpa only [zpow_neg, zpow_natCast, ← inv_pow, Units.val_pow_eq_pow_val]
      using hinv.trans hpow

def evalMonomial (lam : ℂˣ) : Multiplicative G →* Laurent1 where
  toFun v := AddMonoidAlgebra.single v.toAdd.2 ((lam ^ v.toAdd.1 : ℂˣ) : ℂ)
  map_one' := by simp [AddMonoidAlgebra.one_def, -LaurentPolynomial.single_eq_C_mul_T]
  map_mul' u v := by
    simp [zpow_add, Prod.fst_add, Prod.snd_add,
      -LaurentPolynomial.single_eq_C_mul_T]

def evalX (lam : ℂˣ) : Laurent →ₐ[ℂ] Laurent1 :=
  AddMonoidAlgebra.lift ℂ Laurent1 G (evalMonomial lam)

@[simp] theorem evalX_single (lam : ℂˣ) (u : G) (c : ℂ) :
    evalX lam (AddMonoidAlgebra.single u c) =
      AddMonoidAlgebra.single u.2 (c * ((lam ^ u.1 : ℂˣ) : ℂ)) := by
  simp [evalX, evalMonomial, -LaurentPolynomial.single_eq_C_mul_T]

theorem evalX_sum (lam : ℂˣ) (f : Laurent) :
    evalX lam f = f.coeff.sum fun u c =>
      AddMonoidAlgebra.single u.2 (c * ((lam ^ u.1 : ℂˣ) : ℂ)) := by
  rw [evalX, AddMonoidAlgebra.lift_apply]
  simp [evalMonomial, -LaurentPolynomial.single_eq_C_mul_T]

@[simp] theorem evalX_monomial (lam : ℂˣ) (u : G) :
    evalX lam (monomial u) =
      AddMonoidAlgebra.single u.2 ((lam ^ u.1 : ℂˣ) : ℂ) := by
  simp [monomial]

@[simp] theorem evalX_scalar (lam : ℂˣ) (c : ℂ) :
    evalX lam (scalar c) = AddMonoidAlgebra.single 0 c := by
  simp [-LaurentPolynomial.single_eq_C_mul_T]

def includeYHom : ℤ →+ G where
  toFun n := (0, n)
  map_zero' := rfl
  map_add' _ _ := rfl

def includeY : Laurent1 →+* Laurent :=
  AddMonoidAlgebra.mapDomainRingHom ℂ includeYHom

@[simp] theorem includeY_single (n : ℤ) (c : ℂ) :
    includeY (AddMonoidAlgebra.single n c) = AddMonoidAlgebra.single (0, n) c := by
  change AddMonoidAlgebra.mapDomain includeYHom (AddMonoidAlgebra.single n c) = _
  rw [AddMonoidAlgebra.mapDomain_single]
  rfl

@[simp] theorem evalX_includeY (lam : ℂˣ) (f : Laurent1) : evalX lam (includeY f) = f := by
  induction f using AddMonoidAlgebra.induction_linear with
  | zero => simp
  | add f g hf hg => simp [hf, hg]
  | single n c => simp [-LaurentPolynomial.single_eq_C_mul_T]

theorem evalX_surjective (lam : ℂˣ) : Function.Surjective (evalX lam) := by
  intro f
  exact ⟨includeY f, evalX_includeY lam f⟩

theorem includeY_injective : Function.Injective includeY := by
  intro f g h
  simpa using congrArg (evalX (1 : ℂˣ)) h

def reduceX (lam : ℂˣ) : Laurent →+* Laurent := includeY.comp (evalX lam).toRingHom

@[simp] theorem reduceX_single (lam : ℂˣ) (u : G) (c : ℂ) :
    reduceX lam (AddMonoidAlgebra.single u c) =
      AddMonoidAlgebra.single (0, u.2) (c * ((lam ^ u.1 : ℂˣ) : ℂ)) := by
  simp [reduceX, -LaurentPolynomial.single_eq_C_mul_T]

theorem binomial_dvd_x_residue (lam : ℂˣ) (n : ℤ) :
    binomial (1, 0) (lam : ℂ) ∣ monomial (n, 0) - scalar ((lam ^ n : ℂˣ) : ℂ) := by
  have h := unit_sub_dvd_zpow_sub_zpow (monomialUnit (1, 0)) (scalarUnit lam) n
  simpa [binomial, monomialUnit_zpow, scalarUnit_zpow] using h

theorem binomial_dvd_single_residue (lam : ℂˣ) (u : G) (c : ℂ) :
    binomial (1, 0) (lam : ℂ) ∣
      AddMonoidAlgebra.single u c - reduceX lam (AddMonoidAlgebra.single u c) := by
  have h := (binomial_dvd_x_residue lam u.1).mul_left
    (AddMonoidAlgebra.single (0, u.2) c)
  simpa [mul_sub, monomial, scalar_apply, Prod.ext_iff] using h

/-- Every Laurent polynomial differs from its evaluated remainder by a
multiple of the linear factor. -/
theorem binomial_dvd_sub_reduceX (lam : ℂˣ) (f : Laurent) :
    binomial (1, 0) (lam : ℂ) ∣ f - reduceX lam f := by
  induction f using AddMonoidAlgebra.induction_linear with
  | zero => simp
  | add f g hf hg =>
    convert hf.add hg using 1
    simp [map_add, sub_add_sub_comm]
  | single u c => exact binomial_dvd_single_residue lam u c

@[simp] theorem evalX_binomial (lam : ℂˣ) :
    evalX lam (binomial (1, 0) (lam : ℂ)) = 0 := by
  simp [binomial, -LaurentPolynomial.single_eq_C_mul_T]

/-- The evaluation kernel is exactly the principal ideal of `X - lam`. -/
theorem evalX_eq_zero_iff_dvd (lam : ℂˣ) (f : Laurent) :
    evalX lam f = 0 ↔ binomial (1, 0) (lam : ℂ) ∣ f := by
  constructor
  · intro hf
    have h := binomial_dvd_sub_reduceX lam f
    simpa [reduceX, hf] using h
  · rintro ⟨g, rfl⟩
    simp

theorem binomial_x_ne_zero (c : ℂ) : binomial (1, 0) c ≠ 0 := by
  intro h
  have hcoeff := congrArg (fun f : Laurent => f.coeff (1, 0)) h
  simp [binomial, monomial, scalar] at hcoeff

theorem binomial_x_not_isUnit (lam : ℂˣ) : ¬ IsUnit (binomial (1, 0) (lam : ℂ)) := by
  intro h
  have hm := h.map (evalX lam).toRingHom
  change IsUnit (evalX lam (binomial (1, 0) (lam : ℂ))) at hm
  rw [evalX_binomial] at hm
  exact not_isUnit_zero hm

theorem binomial_x_prime (lam : ℂˣ) : Prime (binomial (1, 0) (lam : ℂ)) := by
  refine ⟨binomial_x_ne_zero _, binomial_x_not_isUnit lam, ?_⟩
  intro f g h
  have hzero : evalX lam (f * g) = 0 := (evalX_eq_zero_iff_dvd lam _).mpr h
  rw [map_mul] at hzero
  rcases mul_eq_zero.mp hzero with hf | hg
  · exact Or.inl ((evalX_eq_zero_iff_dvd lam _).mp hf)
  · exact Or.inr ((evalX_eq_zero_iff_dvd lam _).mp hg)

/-- Transport Laurent exponents by an additive lattice automorphism. -/
def changeCoordinates (e : G ≃+ G) : Laurent ≃+* Laurent :=
  AddMonoidAlgebra.mapDomainRingEquiv ℂ e

theorem changeCoordinates_symm (e : G ≃+ G) :
    changeCoordinates e.symm = (changeCoordinates e).symm := by
  simp [changeCoordinates]

@[simp] theorem changeCoordinates_symm_apply (e : G ≃+ G) (f : Laurent) :
    changeCoordinates e.symm (changeCoordinates e f) = f := by
  rw [changeCoordinates_symm]
  simp

@[simp] theorem changeCoordinates_apply_symm (e : G ≃+ G) (f : Laurent) :
    changeCoordinates e (changeCoordinates e.symm f) = f := by
  rw [changeCoordinates_symm]
  simp

@[simp] theorem changeCoordinates_single (e : G ≃+ G) (v : G) (c : ℂ) :
    changeCoordinates e (AddMonoidAlgebra.single v c) =
      AddMonoidAlgebra.single (e v) c := by
  change AddMonoidAlgebra.mapDomain e (AddMonoidAlgebra.single v c) = _
  exact AddMonoidAlgebra.mapDomain_single

@[simp] theorem changeCoordinates_monomial (e : G ≃+ G) (v : G) :
    changeCoordinates e (monomial v) = monomial (e v) := by
  simp [monomial]

@[simp] theorem changeCoordinates_scalar (e : G ≃+ G) (c : ℂ) :
    changeCoordinates e (scalar c) = scalar c := by
  simp

@[simp] theorem changeCoordinates_binomial (e : G ≃+ G) (v : G) (c : ℂ) :
    changeCoordinates e (binomial v c) = binomial (e v) c := by
  simp [binomial]

theorem changeCoordinates_act (e : G ≃+ G) (f : Laurent) (J : G → ℂ) (z : G) :
    Algebra.act (changeCoordinates e f) J (e z) =
      Algebra.act f (fun w => J (e w)) z := by
  simp only [Algebra.act, changeCoordinates, AddMonoidAlgebra.coeff_mapDomainRingEquiv,
    Finsupp.sum_equivMapDomain, map_add]
  rfl

def evalAlong (e : G ≃+ G) (lam : ℂˣ) : Laurent →+* Laurent1 :=
  (evalX lam).toRingHom.comp (changeCoordinates e.symm).toRingHom

@[simp] theorem evalAlong_single (e : G ≃+ G) (lam : ℂˣ) (v : G) (c : ℂ) :
    evalAlong e lam (AddMonoidAlgebra.single v c) =
      AddMonoidAlgebra.single (e.symm v).2 (c * ((lam ^ (e.symm v).1 : ℂˣ) : ℂ)) := by
  simp [evalAlong, -LaurentPolynomial.single_eq_C_mul_T]

theorem evalAlong_eq_zero_iff_dvd (e : G ≃+ G) (lam : ℂˣ) (f : Laurent) :
    evalAlong e lam f = 0 ↔ binomial (e (1, 0)) (lam : ℂ) ∣ f := by
  change evalX lam (changeCoordinates e.symm f) = 0 ↔ _
  rw [evalX_eq_zero_iff_dvd]
  have hfactor : changeCoordinates e.symm (binomial (e (1, 0)) (lam : ℂ)) =
      binomial (1, 0) (lam : ℂ) := by simp
  rw [← hfactor]
  constructor
  · rintro ⟨g, hg⟩
    refine ⟨(changeCoordinates e.symm).symm g, ?_⟩
    apply (changeCoordinates e.symm).injective
    simpa using hg
  · rintro ⟨g, rfl⟩
    exact ⟨changeCoordinates e.symm g, map_mul _ _ _⟩

theorem binomial_along_prime (e : G ≃+ G) (lam : ℂˣ) :
    Prime (binomial (e (1, 0)) (lam : ℂ)) := by
  have h := binomial_x_prime lam
  have hmap := (MulEquiv.prime_iff (changeCoordinates e)).mpr h
  simpa using hmap

/-- Evaluation of another binomial, used to separate prime factors. -/
theorem evalAlong_binomial (e : G ≃+ G) (lam : ℂˣ) (v : G) (c : ℂ) :
    evalAlong e lam (binomial v c) =
      AddMonoidAlgebra.single (e.symm v).2 ((lam ^ (e.symm v).1 : ℂˣ) : ℂ) -
        AddMonoidAlgebra.single 0 c := by
  simp [binomial, evalAlong, -LaurentPolynomial.single_eq_C_mul_T]

theorem binomial_not_dvd_of_transverse_ne_zero (e : G ≃+ G) (lam : ℂˣ)
    (v : G) (c : ℂ) (htransverse : (e.symm v).2 ≠ 0) :
    ¬ binomial (e (1, 0)) (lam : ℂ) ∣ binomial v c := by
  intro h
  have hzero := (evalAlong_eq_zero_iff_dvd e lam _).mpr h
  have hcoeff := congrArg (fun f : Laurent1 => f.coeff (e.symm v).2) hzero
  rw [evalAlong_binomial] at hcoeff
  have hnonzero : ((lam ^ (e.symm v).1 : ℂˣ) : ℂ) ≠ 0 := Units.ne_zero _
  apply hnonzero
  simpa [Finsupp.single_apply, htransverse, Ne.symm htransverse,
    -LaurentPolynomial.single_eq_C_mul_T] using hcoeff

theorem binomial_not_dvd_of_values_ne (e : G ≃+ G) (lam mu : ℂˣ)
    (hne : (lam : ℂ) ≠ (mu : ℂ)) :
    ¬ binomial (e (1, 0)) (lam : ℂ) ∣ binomial (e (1, 0)) (mu : ℂ) := by
  intro h
  have hzero := (evalAlong_eq_zero_iff_dvd e lam _).mpr h
  have hcoeff := congrArg (fun f : Laurent1 => f.coeff 0) hzero
  rw [evalAlong_binomial] at hcoeff
  have hdifference : (lam : ℂ) - (mu : ℂ) = 0 := by
    simpa [Finsupp.single_apply, -LaurentPolynomial.single_eq_C_mul_T] using hcoeff
  exact hne (sub_eq_zero.mp hdifference)

/-- Distinct prime factors assemble without requiring a factorization choice. -/
theorem prod_dvd_of_prime_factors {R : Type*} [CommRing R] [IsDomain R]
    {ι : Type*} (s : Finset ι) (p : ι → R) (f : R)
    (hprime : ∀ i ∈ s, Prime (p i))
    (hseparate : ∀ i ∈ s, ∀ j ∈ s, i ≠ j → ¬ p i ∣ p j)
    (hdivides : ∀ i ∈ s, p i ∣ f) : (∏ i ∈ s, p i) ∣ f := by
  classical
  induction s using Finset.induction_on generalizing f with
  | empty => simp
  | @insert i s hi ih =>
    have hpi := hprime i (Finset.mem_insert_self i s)
    obtain ⟨g, hg⟩ := hdivides i (Finset.mem_insert_self i s)
    have hdivides' : ∀ j ∈ s, p j ∣ g := by
      intro j hj
      have hjinsert : j ∈ insert i s := Finset.mem_insert_of_mem hj
      have hprod : p j ∣ p i * g := hg ▸ hdivides j hjinsert
      rcases (hprime j hjinsert).dvd_or_dvd hprod with hji | hjg
      · exact (hseparate j hjinsert i (Finset.mem_insert_self i s)
          (ne_of_mem_of_not_mem hj hi) hji).elim
      · exact hjg
    have hind := ih g (fun j hj => hprime j (Finset.mem_insert_of_mem hj))
      (fun j hj k hk hne => hseparate j (Finset.mem_insert_of_mem hj)
        k (Finset.mem_insert_of_mem hk) hne) hdivides'
    obtain ⟨q, hq⟩ := hind
    refine ⟨q, ?_⟩
    rw [Finset.prod_insert hi, hg, hq, mul_assoc]

def det (u v : G) : ℤ := u.1 * v.2 - u.2 * v.1

@[simp] theorem det_self (v : G) : det v v = 0 := by simp [det, mul_comm]

theorem det_add_left (u v w : G) : det (u + v) w = det u w + det v w := by
  simp [det]
  ring

theorem det_add_right (u v w : G) : det u (v + w) = det u v + det u w := by
  simp [det]
  ring

theorem det_neg_left (u v : G) : det (-u) v = -det u v := by
  simp [det]
  ring

theorem det_neg_right (u v : G) : det u (-v) = -det u v := by
  simp [det]
  ring

theorem det_swap (u v : G) : det u v = -det v u := by
  simp [det]
  ring

def basisEquiv (v w : G) (hdet : det v w = 1) : G ≃+ G where
  toFun z := (z.1 * v.1 + z.2 * w.1, z.1 * v.2 + z.2 * w.2)
  invFun z := (det z w, det v z)
  left_inv z := by
    have h := hdet
    dsimp [det] at h ⊢
    apply Prod.ext <;> dsimp
    · linear_combination z.1 * h
    · linear_combination z.2 * h
  right_inv z := by
    have h := hdet
    dsimp [det] at h ⊢
    apply Prod.ext <;> dsimp
    · linear_combination z.1 * h
    · linear_combination z.2 * h
  map_add' x y := by
    apply Prod.ext <;> dsimp <;> ring

@[simp] theorem basisEquiv_first (v w : G) (hdet : det v w = 1) :
    basisEquiv v w hdet (1, 0) = v := by ext <;> simp [basisEquiv]

@[simp] theorem basisEquiv_second (v w : G) (hdet : det v w = 1) :
    basisEquiv v w hdet (0, 1) = w := by ext <;> simp [basisEquiv]

@[simp] theorem basisEquiv_symm_apply (v w : G) (hdet : det v w = 1) (z : G) :
    (basisEquiv v w hdet).symm z = (det z w, det v z) := rfl

theorem exists_integral_complement (v : G) (hprimitive : IsCoprime v.1 v.2) :
    ∃ w : G, det v w = 1 := by
  obtain ⟨a, b, hab⟩ := hprimitive
  refine ⟨(-b, a), ?_⟩
  dsimp [det]
  linear_combination hab

theorem binomial_prime_of_integral_basis (v w : G) (hdet : det v w = 1) (lam : ℂˣ) :
    Prime (binomial v (lam : ℂ)) := by
  simpa using binomial_along_prime (basisEquiv v w hdet) lam

theorem binomial_prime_of_primitive (v : G) (hprimitive : IsCoprime v.1 v.2) (lam : ℂˣ) :
    Prime (binomial v (lam : ℂ)) := by
  obtain ⟨w, hw⟩ := exists_integral_complement v hprimitive
  exact binomial_prime_of_integral_basis v w hw lam

theorem binomial_not_dvd_of_det_ne_zero (v w u : G) (hdet : det v w = 1)
    (lam : ℂˣ) (c : ℂ) (hne : det v u ≠ 0) :
    ¬ binomial v (lam : ℂ) ∣ binomial u c := by
  simpa using binomial_not_dvd_of_transverse_ne_zero (basisEquiv v w hdet) lam u c hne

/-! Integer representatives in a half-open fundamental parallelogram. -/

def longitudinalCoordinate (v w z : G) : ℚ := (det z w : ℚ) / (det v w : ℚ)

def transverseCoordinate (v w z : G) : ℚ := (det v z : ℚ) / (det v w : ℚ)

def fundamentalDomain (v w : G) : Set G :=
  {z | 0 ≤ longitudinalCoordinate v w z ∧ longitudinalCoordinate v w z < 1 ∧
    0 ≤ transverseCoordinate v w z ∧ transverseCoordinate v w z < 1}

def fundamentalRepresentative (v w z : G) : G :=
  z - Int.floor (longitudinalCoordinate v w z) • v -
    Int.floor (transverseCoordinate v w z) • w

theorem longitudinalCoordinate_sub_lattice (v w z : G) (hdet : det v w ≠ 0)
    (m n : ℤ) :
    longitudinalCoordinate v w (z - m • v - n • w) =
      longitudinalCoordinate v w z - m := by
  have hd : (det v w : ℚ) ≠ 0 := by exact_mod_cast hdet
  have heq : det (z - m • v - n • w) w = det z w - m * det v w := by
    simp [det]
    ring
  simp only [longitudinalCoordinate, heq, Int.cast_sub, Int.cast_mul]
  field_simp [hd]

theorem transverseCoordinate_sub_lattice (v w z : G) (hdet : det v w ≠ 0)
    (m n : ℤ) :
    transverseCoordinate v w (z - m • v - n • w) =
      transverseCoordinate v w z - n := by
  have hd : (det v w : ℚ) ≠ 0 := by exact_mod_cast hdet
  have heq : det v (z - m • v - n • w) = det v z - n * det v w := by
    simp [det]
    ring
  simp only [transverseCoordinate, heq, Int.cast_sub, Int.cast_mul]
  field_simp [hd]

theorem fundamentalRepresentative_mem (v w z : G) (hdet : det v w ≠ 0) :
    fundamentalRepresentative v w z ∈ fundamentalDomain v w := by
  unfold fundamentalRepresentative fundamentalDomain
  simp only [Set.mem_ofPred_eq]
  rw [longitudinalCoordinate_sub_lattice v w z hdet,
    transverseCoordinate_sub_lattice v w z hdet]
  refine ⟨sub_nonneg.mpr (Int.floor_le _), ?_,
    sub_nonneg.mpr (Int.floor_le _), ?_⟩
  · linarith [Int.lt_floor_add_one (longitudinalCoordinate v w z)]
  · linarith [Int.lt_floor_add_one (transverseCoordinate v w z)]

theorem fundamentalRepresentative_decomposition (v w z : G) :
    z = fundamentalRepresentative v w z +
      Int.floor (longitudinalCoordinate v w z) • v +
      Int.floor (transverseCoordinate v w z) • w := by
  unfold fundamentalRepresentative
  abel

private theorem abs_numerator_le_of_ratio {a b : ℚ} (hb : b ≠ 0)
    (h0 : 0 ≤ a / b) (h1 : a / b ≤ 1) : |a| ≤ |b| := by
  have heq : a / b * b = a := div_mul_cancel₀ a hb
  calc
    |a| = |a / b * b| := congrArg abs heq.symm
    _ = |a / b| * |b| := abs_mul _ _
    _ ≤ 1 * |b| := mul_le_mul_of_nonneg_right (by rwa [abs_of_nonneg h0]) (abs_nonneg _)
    _ = |b| := one_mul _

theorem fundamentalDomain_det_bounds (v w : G) (hdet : det v w ≠ 0)
    {z : G} (hz : z ∈ fundamentalDomain v w) :
    |det v z| ≤ |det v w| ∧ |det w z| ≤ |det v w| := by
  have hd : (det v w : ℚ) ≠ 0 := by exact_mod_cast hdet
  have hfirst := abs_numerator_le_of_ratio hd hz.1 hz.2.1.le
  have hsecond := abs_numerator_le_of_ratio hd hz.2.2.1 hz.2.2.2.le
  have hfirst' : |det z w| ≤ |det v w| := by exact_mod_cast hfirst
  have hsecond' : |det v z| ≤ |det v w| := by exact_mod_cast hsecond
  refine ⟨hsecond', ?_⟩
  rwa [det_swap w z, abs_neg]

theorem fundamentalDomain_finite (v w : G) (hdet : det v w ≠ 0) :
    (fundamentalDomain v w).Finite := by
  have hfinite := Geometry.finite_strip_intersection v w hdet
    (-|det v w|) |det v w| (-|det v w|) |det v w|
  apply hfinite.subset
  intro z hz
  obtain ⟨hv, hw⟩ := fundamentalDomain_det_bounds v w hdet hz
  exact ⟨abs_le.mp hv, abs_le.mp hw⟩

theorem fundamentalDomain_representatives (v w : G) (hdet : det v w ≠ 0) :
    ∀ z : G, ∃ (r : fundamentalDomain v w) (m n : ℤ),
      z = (r : G) + m • v + n • w := by
  intro z
  exact ⟨⟨fundamentalRepresentative v w z, fundamentalRepresentative_mem v w z hdet⟩,
    Int.floor (longitudinalCoordinate v w z),
    Int.floor (transverseCoordinate v w z), fundamentalRepresentative_decomposition v w z⟩

theorem longitudinalCoordinate_add_lattice (v w r : G) (hdet : det v w ≠ 0)
    (m n : ℤ) :
    longitudinalCoordinate v w (r + m • v + n • w) =
      longitudinalCoordinate v w r + m := by
  have h := longitudinalCoordinate_sub_lattice v w (r + m • v + n • w) hdet m n
  have hback : r + m • v + n • w - m • v - n • w = r := by abel
  rw [hback] at h
  linarith

theorem transverseCoordinate_add_lattice (v w r : G) (hdet : det v w ≠ 0)
    (m n : ℤ) :
    transverseCoordinate v w (r + m • v + n • w) =
      transverseCoordinate v w r + n := by
  have h := transverseCoordinate_sub_lattice v w (r + m • v + n • w) hdet m n
  have hback : r + m • v + n • w - m • v - n • w = r := by abel
  rw [hback] at h
  linarith

/-- The exponent set of the finite blocks in Step 2 of §5.2. -/
def exponentBlock (v w : G) (d e : ℕ) : Set G :=
  {z | ∃ r ∈ fundamentalDomain v w, ∃ (i : Fin d) (j : Fin e),
    z = r + (i : ℤ) • v + (j : ℤ) • w}

theorem exponentBlock_eq_range (v w : G) (d e : ℕ) :
    exponentBlock v w d e = Set.range (fun a : fundamentalDomain v w × Fin d × Fin e =>
      (a.1 : G) + (a.2.1 : ℤ) • v + (a.2.2 : ℤ) • w) := by
  ext z
  constructor
  · rintro ⟨r, hr, i, j, rfl⟩
    exact ⟨(⟨r, hr⟩, i, j), rfl⟩
  · rintro ⟨⟨r, i, j⟩, rfl⟩
    exact ⟨r, r.property, i, j, rfl⟩

theorem exponentBlock_finite (v w : G) (hdet : det v w ≠ 0) (d e : ℕ) :
    (exponentBlock v w d e).Finite := by
  let := (fundamentalDomain_finite v w hdet).fintype
  rw [exponentBlock_eq_range]
  exact Set.finite_range _

def blockFinset (v w : G) (hdet : det v w ≠ 0) (d e : ℕ) : Finset G :=
  (exponentBlock_finite v w hdet d e).toFinset

@[simp] theorem mem_blockFinset (v w : G) (hdet : det v w ≠ 0) (d e : ℕ) (z : G) :
    z ∈ blockFinset v w hdet d e ↔ z ∈ exponentBlock v w d e :=
  Set.Finite.mem_toFinset _

/-- Every generating exponent lies in the rectangle of rational lattice
coordinates with side lengths equal to the two recurrence degrees. -/
theorem exponentBlock_coordinate_bounds (v w : G) (hdet : det v w ≠ 0)
    (d e : ℕ) {z : G} (hz : z ∈ exponentBlock v w d e) :
    0 ≤ longitudinalCoordinate v w z ∧ longitudinalCoordinate v w z < d ∧
      0 ≤ transverseCoordinate v w z ∧ transverseCoordinate v w z < e := by
  obtain ⟨r, hr, i, j, rfl⟩ := hz
  rw [longitudinalCoordinate_add_lattice v w r hdet,
    transverseCoordinate_add_lattice v w r hdet]
  have hi0 : (0 : ℚ) ≤ (i : ℤ) := by exact_mod_cast (Nat.zero_le (i : ℕ))
  have hj0 : (0 : ℚ) ≤ (j : ℤ) := by exact_mod_cast (Nat.zero_le (j : ℕ))
  have hi1 : (i : ℚ) + 1 ≤ d := by exact_mod_cast (Nat.succ_le_of_lt i.isLt)
  have hj1 : (j : ℚ) + 1 ≤ e := by exact_mod_cast (Nat.succ_le_of_lt j.isLt)
  rcases hr with ⟨hr0, hr1, hr2, hr3⟩
  push_cast
  push_cast at hi0 hj0
  constructor
  · linarith
  constructor
  · linarith
  constructor <;> linarith

theorem blockFinset_coordinate_bounds (v w : G) (hdet : det v w ≠ 0)
    (d e : ℕ) {z : G} (hz : z ∈ blockFinset v w hdet d e) :
    0 ≤ longitudinalCoordinate v w z ∧ longitudinalCoordinate v w z < d ∧
      0 ≤ transverseCoordinate v w z ∧ transverseCoordinate v w z < e := by
  exact exponentBlock_coordinate_bounds v w hdet d e
    ((mem_blockFinset v w hdet d e z).mp hz)

section PowerReduction

variable {K B : Type*} [Field K] [CommRing B] [Algebra K B]

/-- A unit annihilated by a polynomial with nonzero constant term has its
inverse expressible as a polynomial in the same unit. -/
theorem inverse_eq_polynomial (u : Bˣ) (p : Polynomial K)
    (hconstant : p.coeff 0 ≠ 0) (hroot : Polynomial.aeval (u : B) p = 0) :
    ∃ q : Polynomial K, ((u⁻¹ : Bˣ) : B) = Polynomial.aeval (u : B) q := by
  let q : Polynomial K := -Polynomial.C ((p.coeff 0)⁻¹) * p.divX
  have hrelation := congrArg (Polynomial.aeval (u : B)) (Polynomial.X_mul_divX_add p)
  simp only [map_add, map_mul, Polynomial.aeval_X, Polynomial.aeval_C, hroot] at hrelation
  have hinverse : (u : B) * Polynomial.aeval (u : B) q = 1 := by
    calc
      (u : B) * Polynomial.aeval (u : B) q =
          -(algebraMap K B ((p.coeff 0)⁻¹)) * ((u : B) * Polynomial.aeval (u : B) p.divX) := by
        simp only [q, map_mul, map_neg, Polynomial.aeval_C]
        ring
      _ = -(algebraMap K B ((p.coeff 0)⁻¹)) * -(algebraMap K B (p.coeff 0)) := by
        rw [eq_neg_of_add_eq_zero_left hrelation]
      _ = 1 := by rw [neg_mul_neg, ← map_mul, inv_mul_cancel₀ hconstant, map_one]
  refine ⟨q, ?_⟩
  have h := congrArg (fun x : B => ((u⁻¹ : Bˣ) : B) * x) hinverse
  simpa only [← mul_assoc, Units.inv_mul, one_mul, mul_one] using h.symm

/-- All integer powers, including negative ones, are polynomial expressions. -/
theorem zpow_eq_polynomial (u : Bˣ) (p : Polynomial K)
    (hconstant : p.coeff 0 ≠ 0) (hroot : Polynomial.aeval (u : B) p = 0) (n : ℤ) :
    ∃ q : Polynomial K, ((u ^ n : Bˣ) : B) = Polynomial.aeval (u : B) q := by
  obtain ⟨q, hq⟩ := inverse_eq_polynomial u p hconstant hroot
  cases n with
  | ofNat n => exact ⟨Polynomial.X ^ n, by simp⟩
  | negSucc n =>
    refine ⟨q ^ (n + 1), ?_⟩
    rw [show Int.negSucc n = -((n + 1 : ℕ) : ℤ) by omega, zpow_neg, zpow_natCast,
      ← inv_pow]
    simp [hq]

/-- Reduction by a monic relation leaves the evaluation unchanged. -/
theorem aeval_modByMonic (u : B) (p q : Polynomial K)
    (hroot : Polynomial.aeval u p = 0) :
    Polynomial.aeval u (q %ₘ p) = Polynomial.aeval u q := by
  conv_rhs => rw [← Polynomial.modByMonic_add_div q p]
  simp [map_add, map_mul, hroot]

/-- Step 2 of Lemma 5.2: integer powers reduce to the first `degree p` powers. -/
theorem zpow_mem_span_initial_powers (u : Bˣ) (p : Polynomial K) (hmonic : p.Monic)
    (hconstant : p.coeff 0 ≠ 0) (hroot : Polynomial.aeval (u : B) p = 0) (n : ℤ) :
    ((u ^ n : Bˣ) : B) ∈
      Submodule.span K (Set.range fun i : Fin p.natDegree => (u : B) ^ (i : ℕ)) := by
  obtain ⟨q, hq⟩ := zpow_eq_polynomial u p hconstant hroot n
  apply PowerBasis.mem_span_pow'.mpr
  refine ⟨q %ₘ p, ?_, ?_⟩
  · exact (Polynomial.degree_modByMonic_lt q hmonic).trans_le p.degree_le_natDegree
  · rw [aeval_modByMonic (u : B) p q hroot]
    exact hq

theorem mul_mem_span_product_ranges {ι κ : Type*} (a : ι → B) (b : κ → B)
    {x y : B} (hx : x ∈ Submodule.span K (Set.range a))
    (hy : y ∈ Submodule.span K (Set.range b)) :
    x * y ∈ Submodule.span K (Set.range fun j : ι × κ => a j.1 * b j.2) := by
  have h := Submodule.mul_mem_mul hx hy
  rw [Submodule.span_mul_span] at h
  apply Submodule.span_mono _ h
  rintro z ⟨x, ⟨i, rfl⟩, y, ⟨j, rfl⟩, rfl⟩
  exact ⟨(i, j), rfl⟩

/-- Two independent Laurent recurrences give a finite rectangle of powers. -/
theorem zpow_mul_zpow_mem_span (u w : Bˣ) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hpu : Polynomial.aeval (u : B) p = 0) (hqw : Polynomial.aeval (w : B) q = 0)
    (m n : ℤ) :
    ((u ^ m : Bˣ) : B) * ((w ^ n : Bˣ) : B) ∈ Submodule.span K
      (Set.range fun j : Fin p.natDegree × Fin q.natDegree =>
        (u : B) ^ (j.1 : ℕ) * (w : B) ^ (j.2 : ℕ)) := by
  exact mul_mem_span_product_ranges
    (fun i : Fin p.natDegree => (u : B) ^ (i : ℕ))
    (fun j : Fin q.natDegree => (w : B) ^ (j : ℕ))
    (zpow_mem_span_initial_powers u p hp hp0 hpu m)
    (zpow_mem_span_initial_powers w q hq hq0 hqw n)

def monomialUnitOver (v : G) : (AddMonoidAlgebra K G)ˣ where
  val := AddMonoidAlgebra.single v 1
  inv := AddMonoidAlgebra.single (-v) 1
  val_inv := by simp [AddMonoidAlgebra.one_def]
  inv_val := by simp [AddMonoidAlgebra.one_def]

@[simp] theorem monomialUnitOver_val (v : G) :
    (monomialUnitOver (K := K) v : AddMonoidAlgebra K G) = AddMonoidAlgebra.single v 1 := rfl

theorem monomialUnitOver_add (v w : G) :
    monomialUnitOver (K := K) (v + w) = monomialUnitOver v * monomialUnitOver w := by
  ext
  simp

theorem monomialUnitOver_zpow (v : G) (n : ℤ) :
    (monomialUnitOver (K := K) v) ^ n = monomialUnitOver (n • v) := by
  cases n with
  | ofNat n => ext; simp [AddMonoidAlgebra.single_pow]
  | negSucc n =>
    rw [show Int.negSucc n = -((n + 1 : ℕ) : ℤ) by omega, zpow_neg, zpow_natCast,
      ← inv_pow]
    ext
    simp [monomialUnitOver, AddMonoidAlgebra.single_pow]
    congr 1
    ext <;> ring

def imageMonomial (rho : AddMonoidAlgebra K G →ₐ[K] B) (v : G) : B :=
  rho (AddMonoidAlgebra.single v 1)

def imageUnit (rho : AddMonoidAlgebra K G →ₐ[K] B) (v : G) : Bˣ :=
  Units.map rho.toMonoidHom (monomialUnitOver v)

@[simp] theorem imageUnit_val (rho : AddMonoidAlgebra K G →ₐ[K] B) (v : G) :
    (imageUnit rho v : B) = imageMonomial rho v := rfl

@[simp] theorem imageMonomial_add (rho : AddMonoidAlgebra K G →ₐ[K] B) (v w : G) :
    imageMonomial rho (v + w) = imageMonomial rho v * imageMonomial rho w := by
  simp [imageMonomial, ← map_mul]

theorem imageUnit_zpow (rho : AddMonoidAlgebra K G →ₐ[K] B) (v : G) (n : ℤ) :
    ((imageUnit rho v ^ n : Bˣ) : B) = imageMonomial rho (n • v) := by
  rw [imageUnit, ← map_zpow, monomialUnitOver_zpow]
  rfl

def representativePowers {ι : Type*} (rho : AddMonoidAlgebra K G →ₐ[K] B)
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (j : ι × Fin p.natDegree × Fin q.natDegree) : B :=
  imageMonomial rho (r j.1) * imageMonomial rho v ^ (j.2.1 : ℕ) *
    imageMonomial rho w ^ (j.2.2 : ℕ)

theorem representative_powers_span_monomial {ι : Type*}
    (rho : AddMonoidAlgebra K G →ₐ[K] B) (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hpu : Polynomial.aeval (imageMonomial rho v) p = 0)
    (hqw : Polynomial.aeval (imageMonomial rho w) q = 0)
    (z : G) (hrep : ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    imageMonomial rho z ∈ Submodule.span K (Set.range (representativePowers rho r v w p q)) := by
  obtain ⟨i, m, n, rfl⟩ := hrep
  rw [imageMonomial_add, imageMonomial_add, ← imageUnit_zpow, ← imageUnit_zpow]
  have hprod := zpow_mul_zpow_mem_span (imageUnit rho v) (imageUnit rho w)
    p q hp hq hp0 hq0 hpu hqw m n
  have hleft : imageMonomial rho (r i) ∈ Submodule.span K (Set.range fun i => imageMonomial rho (r i)) :=
    Submodule.subset_span ⟨i, rfl⟩
  have h := mul_mem_span_product_ranges (fun i => imageMonomial rho (r i))
    (fun j : Fin p.natDegree × Fin q.natDegree =>
      imageMonomial rho v ^ (j.1 : ℕ) * imageMonomial rho w ^ (j.2 : ℕ)) hleft hprod
  have hsets : Set.range (fun j : ι × (Fin p.natDegree × Fin q.natDegree) =>
      imageMonomial rho (r j.1) * (imageMonomial rho v ^ (j.2.1 : ℕ) *
        imageMonomial rho w ^ (j.2.2 : ℕ))) = Set.range (representativePowers rho r v w p q) := by
    congr 1
    funext j
    simp [representativePowers, mul_assoc]
  rw [hsets] at h
  simpa only [imageUnit_val, mul_assoc] using h

theorem representative_powers_span_image {ι : Type*}
    (rho : AddMonoidAlgebra K G →ₐ[K] B) (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hpu : Polynomial.aeval (imageMonomial rho v) p = 0)
    (hqw : Polynomial.aeval (imageMonomial rho w) q = 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w)
    (f : AddMonoidAlgebra K G) :
    rho f ∈ Submodule.span K (Set.range (representativePowers rho r v w p q)) := by
  induction f using AddMonoidAlgebra.induction_linear with
  | zero => simp
  | add f g hf hg => exact map_add rho f g ▸ Submodule.add_mem _ hf hg
  | single z c =>
    have h := representative_powers_span_monomial rho r v w p q hp hq hp0 hq0 hpu hqw z (hrep z)
    have hscalar := Submodule.smul_mem _ c h
    simpa [imageMonomial, ← map_smul] using hscalar

/-- With complete coset representatives, the finite blocks span the quotient algebra. -/
theorem representative_powers_span_top {ι : Type*}
    (rho : AddMonoidAlgebra K G →ₐ[K] B) (hsurjective : Function.Surjective rho)
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hpu : Polynomial.aeval (imageMonomial rho v) p = 0)
    (hqw : Polynomial.aeval (imageMonomial rho w) q = 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Submodule.span K (Set.range (representativePowers rho r v w p q)) = ⊤ := by
  apply top_unique
  intro y _
  obtain ⟨f, rfl⟩ := hsurjective y
  exact representative_powers_span_image rho r v w p q hp hq hp0 hq0 hpu hqw hrep f

theorem representative_powers_finrank_le {ι : Type*} [Fintype ι]
    (rho : AddMonoidAlgebra K G →ₐ[K] B) (hsurjective : Function.Surjective rho)
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hpu : Polynomial.aeval (imageMonomial rho v) p = 0)
    (hqw : Polynomial.aeval (imageMonomial rho w) q = 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Module.finrank K B ≤ Fintype.card ι * p.natDegree * q.natDegree := by
  have hspan := representative_powers_span_top rho hsurjective r v w p q
    hp hq hp0 hq0 hpu hqw hrep
  have hbound := finrank_le_of_span_eq_top hspan
  simpa [Fintype.card_prod, Nat.mul_assoc] using hbound

theorem representative_powers_moduleFinite {ι : Type*} [Fintype ι]
    (rho : AddMonoidAlgebra K G →ₐ[K] B) (hsurjective : Function.Surjective rho)
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hpu : Polynomial.aeval (imageMonomial rho v) p = 0)
    (hqw : Polynomial.aeval (imageMonomial rho w) q = 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) : Module.Finite K B := by
  classical
  have hspan := representative_powers_span_top rho hsurjective r v w p q
    hp hq hp0 hq0 hpu hqw hrep
  apply Module.Finite.of_fg_top
  refine ⟨Finset.univ.image (representativePowers rho r v w p q), ?_⟩
  simpa only [Finset.coe_image, Finset.coe_univ, Set.image_univ] using hspan

def twoRelationIdeal (v w : G) (p q : Polynomial K) : Ideal (AddMonoidAlgebra K G) :=
  Ideal.span {Polynomial.aeval (AddMonoidAlgebra.single v 1) p,
    Polynomial.aeval (AddMonoidAlgebra.single w 1) q}

abbrev twoRelationQuotient (v w : G) (p q : Polynomial K) :=
  AddMonoidAlgebra K G ⧸ twoRelationIdeal v w p q

def relationProjection (v w : G) (p q : Polynomial K) :
    AddMonoidAlgebra K G →ₐ[K] twoRelationQuotient v w p q :=
  Ideal.Quotient.mkₐ K (twoRelationIdeal v w p q)

theorem relationProjection_surjective (v w : G) (p q : Polynomial K) :
    Function.Surjective (relationProjection v w p q) := Ideal.Quotient.mkₐ_surjective K _

theorem first_relation_zero (v w : G) (p q : Polynomial K) :
    Polynomial.aeval (imageMonomial (relationProjection v w p q) v) p = 0 := by
  unfold imageMonomial
  rw [Polynomial.aeval_algHom_apply]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Set.mem_insert _ _)

theorem second_relation_zero (v w : G) (p q : Polynomial K) :
    Polynomial.aeval (imageMonomial (relationProjection v w p q) w) q = 0 := by
  unfold imageMonomial
  rw [Polynomial.aeval_algHom_apply]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_singleton _))

/-- A concrete two-relation Laurent quotient is generated by the lattice
representatives times the finite rectangle of initial powers. -/
theorem twoRelationQuotient_span {ι : Type*} (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Submodule.span K (Set.range
      (representativePowers (relationProjection v w p q) r v w p q)) = ⊤ := by
  exact representative_powers_span_top (relationProjection v w p q)
    (relationProjection_surjective v w p q) r v w p q hp hq hp0 hq0
    (first_relation_zero v w p q) (second_relation_zero v w p q) hrep

theorem twoRelationQuotient_finrank_le {ι : Type*} [Fintype ι]
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Module.finrank K (twoRelationQuotient v w p q) ≤ Fintype.card ι * p.natDegree * q.natDegree := by
  exact representative_powers_finrank_le (relationProjection v w p q)
    (relationProjection_surjective v w p q) r v w p q hp hq hp0 hq0
    (first_relation_zero v w p q) (second_relation_zero v w p q) hrep

theorem twoRelationQuotient_moduleFinite {ι : Type*} [Fintype ι]
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp : p.Monic) (hq : q.Monic) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Module.Finite K (twoRelationQuotient v w p q) := by
  exact representative_powers_moduleFinite (relationProjection v w p q)
    (relationProjection_surjective v w p q) r v w p q hp hq hp0 hq0
    (first_relation_zero v w p q) (second_relation_zero v w p q) hrep

/-! The recurrence polynomials in the paper need not be monic. Scaling by
the inverse leading coefficient preserves their degree, roots, and nonzero
constant coefficient, so the preceding finite blocks apply unchanged. -/

def monicRelation (p : Polynomial K) : Polynomial K :=
  p * Polynomial.C p.leadingCoeff⁻¹

theorem relation_ne_zero_of_constant_ne_zero {p : Polynomial K}
    (hp0 : p.coeff 0 ≠ 0) : p ≠ 0 := by
  intro hp
  apply hp0
  simp [hp]

theorem monicRelation_monic {p : Polynomial K} (hp : p ≠ 0) :
    (monicRelation p).Monic := Polynomial.monic_mul_leadingCoeff_inv hp

@[simp] theorem monicRelation_natDegree {p : Polynomial K} (hp : p ≠ 0) :
    (monicRelation p).natDegree = p.natDegree := by
  exact Polynomial.natDegree_mul_C (inv_ne_zero (Polynomial.leadingCoeff_ne_zero.mpr hp))

theorem monicRelation_constant_ne_zero {p : Polynomial K} (hp0 : p.coeff 0 ≠ 0) :
    (monicRelation p).coeff 0 ≠ 0 := by
  have hp := relation_ne_zero_of_constant_ne_zero hp0
  simp only [monicRelation, Polynomial.coeff_mul_C]
  exact mul_ne_zero hp0 (inv_ne_zero (Polynomial.leadingCoeff_ne_zero.mpr hp))

theorem monicRelation_aeval_zero {p : Polynomial K} {b : B}
    (hp : Polynomial.aeval b p = 0) : Polynomial.aeval b (monicRelation p) = 0 := by
  simp [monicRelation, hp]

theorem twoRelationQuotient_span_of_constant_ne_zero {ι : Type*}
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Submodule.span K (Set.range
      (representativePowers (relationProjection v w p q) r v w p q)) = ⊤ := by
  have hp := relation_ne_zero_of_constant_ne_zero hp0
  have hq := relation_ne_zero_of_constant_ne_zero hq0
  have hspan := representative_powers_span_top (relationProjection v w p q)
    (relationProjection_surjective v w p q) r v w (monicRelation p) (monicRelation q)
    (monicRelation_monic hp) (monicRelation_monic hq)
    (monicRelation_constant_ne_zero hp0) (monicRelation_constant_ne_zero hq0)
    (monicRelation_aeval_zero (first_relation_zero v w p q))
    (monicRelation_aeval_zero (second_relation_zero v w p q)) hrep
  apply top_unique
  rw [← hspan]
  apply Submodule.span_mono
  rintro y ⟨a, rfl⟩
  let i : Fin p.natDegree := ⟨a.2.1.val, by
    rw [← monicRelation_natDegree hp]
    exact a.2.1.isLt⟩
  let j : Fin q.natDegree := ⟨a.2.2.val, by
    rw [← monicRelation_natDegree hq]
    exact a.2.2.isLt⟩
  exact ⟨(a.1, i, j), rfl⟩

theorem twoRelationQuotient_finrank_le_of_constant_ne_zero {ι : Type*} [Fintype ι]
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Module.finrank K (twoRelationQuotient v w p q) ≤
      Fintype.card ι * p.natDegree * q.natDegree := by
  have hspan := twoRelationQuotient_span_of_constant_ne_zero r v w p q hp0 hq0 hrep
  have hbound := finrank_le_of_span_eq_top hspan
  simpa [Fintype.card_prod, Nat.mul_assoc] using hbound

theorem twoRelationQuotient_moduleFinite_of_constant_ne_zero {ι : Type*} [Fintype ι]
    (r : ι → G) (v w : G) (p q : Polynomial K)
    (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0)
    (hrep : ∀ z : G, ∃ (i : ι) (m n : ℤ), z = r i + m • v + n • w) :
    Module.Finite K (twoRelationQuotient v w p q) := by
  classical
  have hspan := twoRelationQuotient_span_of_constant_ne_zero r v w p q hp0 hq0 hrep
  apply Module.Finite.of_fg_top
  refine ⟨Finset.univ.image (representativePowers (relationProjection v w p q) r v w p q), ?_⟩
  simpa only [Finset.coe_image, Finset.coe_univ, Set.image_univ] using hspan

/-- The original half-open parallelogram supplies complete representatives;
there is no separate hypothesis asserting their existence. -/
theorem fundamental_blocks_span (v w : G) (hdet : det v w ≠ 0) (p q : Polynomial K)
    (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Submodule.span K (Set.range
      (representativePowers (relationProjection v w p q)
        (Subtype.val : fundamentalDomain v w → G) v w p q)) = ⊤ := by
  exact twoRelationQuotient_span_of_constant_ne_zero Subtype.val v w p q hp0 hq0
    (fundamentalDomain_representatives v w hdet)

theorem representativePowers_eq_imageMonomial {ι : Type*}
    (rho : AddMonoidAlgebra K G →ₐ[K] B) (r : ι → G) (v w : G)
    (p q : Polynomial K) (a : ι × Fin p.natDegree × Fin q.natDegree) :
    representativePowers rho r v w p q a =
      imageMonomial rho (r a.1 + (a.2.1 : ℤ) • v + (a.2.2 : ℤ) • w) := by
  have hn (u : G) (n : ℕ) :
      imageMonomial rho ((n : ℤ) • u) = imageMonomial rho u ^ n := by
    simpa [zpow_natCast] using (imageUnit_zpow rho u (n : ℤ)).symm
  unfold representativePowers
  rw [imageMonomial_add, imageMonomial_add, hn v a.2.1.val, hn w a.2.2.val]

/-- The finite exponent block itself, rather than an abstract family of
vectors, gives a generating set for the concrete Laurent quotient. -/
theorem exponentBlock_monomials_span (v w : G) (hdet : det v w ≠ 0)
    (p q : Polynomial K) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Submodule.span K (imageMonomial (relationProjection v w p q) ''
      exponentBlock v w p.natDegree q.natDegree) = ⊤ := by
  apply top_unique
  rw [← fundamental_blocks_span v w hdet p q hp0 hq0]
  apply Submodule.span_mono
  rintro y ⟨a, rfl⟩
  rw [representativePowers_eq_imageMonomial]
  exact ⟨_, ⟨a.1, a.1.property, a.2.1, a.2.2, rfl⟩, rfl⟩

theorem blockFinset_monomials_span (v w : G) (hdet : det v w ≠ 0)
    (p q : Polynomial K) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Submodule.span K (imageMonomial (relationProjection v w p q) ''
      (blockFinset v w hdet p.natDegree q.natDegree : Set G)) = ⊤ := by
  simpa only [blockFinset, Set.Finite.coe_toFinset] using
    exponentBlock_monomials_span v w hdet p q hp0 hq0

theorem fundamental_blocks_finrank_le (v w : G) (hdet : det v w ≠ 0)
    (p q : Polynomial K) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Module.finrank K (twoRelationQuotient v w p q) ≤
      (fundamentalDomain v w).ncard * p.natDegree * q.natDegree := by
  classical
  let := (fundamentalDomain_finite v w hdet).fintype
  simpa using twoRelationQuotient_finrank_le_of_constant_ne_zero
    (Subtype.val : fundamentalDomain v w → G) v w p q hp0 hq0
    (fundamentalDomain_representatives v w hdet)

theorem fundamental_blocks_moduleFinite (v w : G) (hdet : det v w ≠ 0)
    (p q : Polynomial K) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Module.Finite K (twoRelationQuotient v w p q) := by
  classical
  let := (fundamentalDomain_finite v w hdet).fintype
  exact twoRelationQuotient_moduleFinite_of_constant_ne_zero
    (Subtype.val : fundamentalDomain v w → G) v w p q hp0 hq0
    (fundamentalDomain_representatives v w hdet)

/-- Substituting a nonzero scalar multiple of the variable describes the
second relation `A_j(X^v_j Y^(-v_j))` over the coefficient field. -/
def scaledRelation (p : Polynomial K) (a : K) : Polynomial K :=
  p.comp (Polynomial.C a * Polynomial.X)

@[simp] theorem scaledRelation_constant (p : Polynomial K) (a : K) :
    (scaledRelation p a).coeff 0 = p.coeff 0 := by
  simp [Polynomial.coeff_zero_eq_eval_zero, scaledRelation, Polynomial.eval_comp]

@[simp] theorem scaledRelation_natDegree (p : Polynomial K) {a : K} (ha : a ≠ 0) :
    (scaledRelation p a).natDegree = p.natDegree := by
  simp only [scaledRelation, Polynomial.natDegree_comp,
    Polynomial.natDegree_C_mul_X a ha, Nat.mul_one]

theorem scaledRelation_aeval (p : Polynomial K) (a : K) (b : B) :
    Polynomial.aeval b (scaledRelation p a) =
      Polynomial.aeval (algebraMap K B a * b) p := by
  simp [scaledRelation, Polynomial.aeval_comp]

theorem scaledRelation_constant_ne_zero {p : Polynomial K} (hp0 : p.coeff 0 ≠ 0)
    (a : K) : (scaledRelation p a).coeff 0 ≠ 0 := by
  simpa using hp0

theorem scaled_fundamental_blocks_span (v w : G) (hdet : det v w ≠ 0)
    (p q : Polynomial K) (a : K) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Submodule.span K (Set.range
      (representativePowers (relationProjection v w p (scaledRelation q a))
        (Subtype.val : fundamentalDomain v w → G) v w p (scaledRelation q a))) = ⊤ := by
  exact fundamental_blocks_span v w hdet p (scaledRelation q a) hp0
    (scaledRelation_constant_ne_zero hq0 a)

theorem scaled_fundamental_blocks_finrank_le (v w : G) (hdet : det v w ≠ 0)
    (p q : Polynomial K) {a : K} (ha : a ≠ 0)
    (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Module.finrank K (twoRelationQuotient v w p (scaledRelation q a)) ≤
      (fundamentalDomain v w).ncard * p.natDegree * q.natDegree := by
  simpa only [scaledRelation_natDegree q ha] using
    fundamental_blocks_finrank_le v w hdet p (scaledRelation q a) hp0
      (scaledRelation_constant_ne_zero hq0 a)

theorem scaled_fundamental_blocks_moduleFinite (v w : G) (hdet : det v w ≠ 0)
    (p q : Polynomial K) (a : K) (hp0 : p.coeff 0 ≠ 0) (hq0 : q.coeff 0 ≠ 0) :
    Module.Finite K (twoRelationQuotient v w p (scaledRelation q a)) := by
  exact fundamental_blocks_moduleFinite v w hdet p (scaledRelation q a) hp0
    (scaledRelation_constant_ne_zero hq0 a)

end PowerReduction

end

end NivatTrial.Divisibility

