import NivatTrial.AmbiguityPropagation

/-! Actual one-sided and two-sided nonexpansiveness of the orbit closure. The
orientation is a nonzero real vector; rationality is a theorem to be deduced
from generating windows, not part of the definition. -/

namespace NivatTrial.Nonexpansive

open NivatTrial.Dynamics NivatTrial.Zonotope
open scoped Classical

noncomputable section

abbrev G := ℤ × ℤ
abbrev Plane := ℝ × ℝ

/-- Signed distance up to a positive scale from the oriented line generated by
`v`. Its nonnegative half-plane lies to the left of `v`. -/
def score (v : Plane) (z : G) : ℝ := v.1 * z.2 - v.2 * z.1

@[simp] theorem score_zero (v : Plane) : score v 0 = 0 := by simp [score]

theorem score_add (v : Plane) (z w : G) :
    score v (z + w) = score v z + score v w := by
  simp [score, Prod.fst_add, Prod.snd_add]
  ring

theorem score_neg (v : Plane) (z : G) : score v (-z) = -score v z := by
  simp [score]
  ring

theorem score_sub (v : Plane) (z w : G) :
    score v (z - w) = score v z - score v w := by
  simpa [sub_eq_add_neg, score_neg] using score_add v z (-w)

theorem score_nsmul (v : Plane) (z : G) (n : ℕ) :
    score v (n • z) = (n : ℝ) * score v z := by
  simp [score, nsmul_eq_mul]
  ring

theorem score_zsmul (v : Plane) (z : G) (n : ℤ) :
    score v (n • z) = (n : ℝ) * score v z := by
  simp [score, zsmul_eq_mul]
  ring

theorem score_neg_direction (v : Plane) (z : G) :
    score (-v) z = -score v z := by
  simp [score]
  ring

def halfPlane (v : Plane) (c : ℝ := 0) : Set G := {z | c ≤ score v z}

@[simp] theorem mem_halfPlane (v : Plane) (c : ℝ) (z : G) :
    z ∈ halfPlane v c ↔ c ≤ score v z := Iff.rfl

def strip (v : Plane) (r : ℝ) : Set G := {z | |score v z| ≤ r}

@[simp] theorem mem_strip (v : Plane) (r : ℝ) (z : G) :
    z ∈ strip v r ↔ |score v z| ≤ r := Iff.rfl

def AgreeOn {A : Type*} (x y : G → A) (R : Set G) : Prop :=
  ∀ z ∈ R, x z = y z

theorem agreeOn_subset {A : Type*} {x y : G → A} {R Q : Set G}
    (hR : AgreeOn x y R) (hQR : Q ⊆ R) : AgreeOn x y Q :=
  fun z hz => hR z (hQR hz)

/-- This quantifies over actual finite-window limits of translates. -/
def OneSidedNonexpansive {A : Type*} (θ : G → A) (v : Plane) : Prop :=
  ∃ x ∈ languageHull θ, ∃ y ∈ languageHull θ,
    x ≠ y ∧ AgreeOn x y (halfPlane v 0)

def OneSidedExpansive {A : Type*} (θ : G → A) (v : Plane) : Prop :=
  ¬OneSidedNonexpansive θ v

def LineNonexpansive {A : Type*} (θ : G → A) (v : Plane) : Prop :=
  ∀ r : ℝ, 0 ≤ r → ∃ x ∈ languageHull θ, ∃ y ∈ languageHull θ,
    x ≠ y ∧ AgreeOn x y (strip v r)

theorem oneSidedNonexpansive_of_hull {A : Type*} {θ ξ : G → A}
    (hξ : ξ ∈ languageHull θ) {v : Plane}
    (h : OneSidedNonexpansive ξ v) : OneSidedNonexpansive θ v := by
  obtain ⟨x, hx, y, hy, hxy, hagree⟩ := h
  exact ⟨x, languageHull_trans hξ hx, y, languageHull_trans hξ hy, hxy, hagree⟩

theorem oneSidedNonexpansive_shift {A : Type*} (θ : G → A)
    (u : G) (v : Plane) :
    OneSidedNonexpansive (shift u θ) v ↔ OneSidedNonexpansive θ v := by
  simp only [OneSidedNonexpansive, languageHull_shift]

theorem oneSidedExpansive_of_hull {A : Type*} {θ ξ : G → A}
    (hξ : ξ ∈ languageHull θ) {v : Plane}
    (h : OneSidedExpansive θ v) : OneSidedExpansive ξ v :=
  fun hn => h (oneSidedNonexpansive_of_hull hξ hn)

theorem oneSidedNonexpansive_has_outside_disagreement {A : Type*}
    {θ : G → A} {v : Plane} (h : OneSidedNonexpansive θ v) :
    ∃ x ∈ languageHull θ, ∃ y ∈ languageHull θ,
      ∃ z : G, score v z < 0 ∧ x z ≠ y z := by
  obtain ⟨x, hx, y, hy, hxy, hagree⟩ := h
  have hz : ∃ z, x z ≠ y z := by
    by_contra h
    apply hxy
    funext z
    by_contra hne
    exact h ⟨z, hne⟩
  obtain ⟨z, hne⟩ := hz
  refine ⟨x, hx, y, hy, z, ?_, hne⟩
  by_contra hn
  exact hne (hagree z (by change (0 : ℝ) ≤ score v z; exact le_of_not_gt hn))

theorem exists_positive_score {v : Plane} (hv : v ≠ 0) :
    ∃ g : G, 0 < score v g := by
  by_cases hfirst : v.1 = 0
  · have hsecond : v.2 ≠ 0 := by
      intro hz
      exact hv (Prod.ext hfirst hz)
    rcases lt_or_gt_of_ne hsecond with hneg | hpos
    · exact ⟨(1, 0), by simp [score]; linarith⟩
    · exact ⟨(-1, 0), by simp [score]; linarith⟩
  · rcases lt_or_gt_of_ne hfirst with hneg | hpos
    · exact ⟨(0, -1), by simp [score]; linarith⟩
    · exact ⟨(0, 1), by simp [score]; linarith⟩

/-- An ambiguity on a half-plane supplies ambiguity on every strip around its
boundary line. This is the elementary direction of the NEL/ONED relation. -/
theorem lineNonexpansive_of_oneSided {A : Type*} {θ : G → A} {v : Plane}
    (hv : v ≠ 0) (h : OneSidedNonexpansive θ v) : LineNonexpansive θ v := by
  obtain ⟨x, hx, y, hy, hxy, hagree⟩ := h
  obtain ⟨g, hg⟩ := exists_positive_score hv
  intro r hr
  obtain ⟨n, hn⟩ := exists_nat_gt (r / score v g)
  let u : G := n • g
  have hu : r ≤ score v u := by
    rw [show score v u = (n : ℝ) * score v g by exact score_nsmul v g n]
    have hmul := (div_lt_iff₀ hg).mp hn
    nlinarith
  refine ⟨shift u x, shift_mem_languageHull hx u,
    shift u y, shift_mem_languageHull hy u,
    fun heq => hxy (shift_injective u heq), ?_⟩
  intro z hz
  change x (u + z) = y (u + z)
  apply hagree
  change (0 : ℝ) ≤ score v (u + z)
  rw [score_add]
  have hzl := (abs_le.mp (show |score v z| ≤ r from hz)).1
  linarith

end

end NivatTrial.Nonexpansive
