import NivatTrial.QuotientLinear
import NivatTrial.SupportGeometry

/-! Lemma 5.2: the actual two-relation Laurent quotient is generated by the
monomials whose lattice exponents lie in the difference zonotope. -/

namespace NivatTrial.QuotientSpanning

open NivatTrial.Algebra NivatTrial.Divisibility NivatTrial.CoefficientField
open NivatTrial.QuotientIdeals NivatTrial.QuotientLinear NivatTrial.SupportGeometry
open NivatTrial.Zonotope
open scoped Classical Pointwise

noncomputable section

variable {ι : Type*} [Fintype ι]

def differenceRegion (v : ι → G) (S : ι → Finset ℂˣ) : Set G :=
  {d | embed d ∈ zonotope (fun i => (S i).card • v i) -
    zonotope (fun i => (S i).card • v i)}

theorem projection_mem_span_of_support (v : ι → G) (S : ι → Finset ℂˣ)
    (B : Set G) (f : R) (hf : ∀ z ∈ f.coeff.support, z ∈ B) :
    projection v S f ∈ Submodule.span K
      ((fun d : G => projection v S (AddMonoidAlgebra.single d 1)) '' B) := by
  let N := Submodule.span K
    ((fun d : G => projection v S (AddMonoidAlgebra.single d 1)) '' B)
  have hle : Submodule.span K (AddMonoidAlgebra.of' K G '' (f.coeff.support : Set G)) ≤
      N.comap (projection v S).toLinearMap := by
    apply Submodule.span_le.mpr
    rintro r ⟨z, hz, rfl⟩
    exact Submodule.subset_span ⟨z, hf z hz, rfl⟩
  exact hle (AddMonoidAlgebra.mem_span_support_coeff f)

/-- The coefficient field, ideal, generators and zonotope in this theorem are
all explicitly constructed.  No coprimality or spanning premise remains. -/
theorem lemma5_2 (v : ι → G) (S : ι → Finset ℂˣ)
    (hv : ∀ i, v i ≠ 0) (hdet : ∀ i j, i ≠ j → det (v i) (v j) ≠ 0) :
    Submodule.span K ((fun d : G => projection v S (AddMonoidAlgebra.single d 1)) ''
      differenceRegion v S) = ⊤ := by
  apply global_span_of_projector_blocks v S hv hdet
  intro i j hij e he
  have hneg : det (v i) (-v j) ≠ 0 := by
    simpa only [show det (v i) (-v j) = -det (v i) (v j) from
      Geometry.det_neg_right (v i) (v j), neg_ne_zero] using hdet i j hij
  apply projection_mem_span_of_support
  intro z hz
  exact projector_support v S i j hij hneg e
    ((mem_blockFinset (v i) (-v j) hneg (S i).card (S j).card e).mpr he) z hz

end

end NivatTrial.QuotientSpanning
